# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
     - name: example ec2 group
       ec2_group:
         name: default
         description: an example EC2 group
         region: us-east-1
         rules:
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 443
             to_port: 443
             cidr_ip: 0.0.0.0/0
         name: default
         description: Update Default to support Mysql
         region: us-east-1
         rules:
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 3306
             to_port: 3306
             cidr_ip: 0.0.0.0/0
